/**
 * Schema for a single scraped section (chapter) of the Mahabharata.
 *
 * One file per section is stored under `public/data/{parvaSlug}/{padded3}.json`,
 * e.g. `public/data/m01/001.json`. The scraper script generates them.
 */
export interface SectionData {
  parva: number;
  parvaSlug: string;
  parvaName: string;
  section: number;
  /** Optional title scraped from the page (often "SECTION I"). */
  title?: string;
  /** Paragraphs of the translation, in order. May contain editorial notes. */
  paragraphs: string[];
  /** Source URL on sacred-texts.com. */
  source: string;
}

/** Manifest of which sections are present locally. Generated by the scraper. */
export interface SectionsManifest {
  /** Map of parva slug -> sorted array of section numbers available. */
  available: Record<string, number[]>;
  /** When the scrape finished (ISO string). */
  generatedAt?: string;
}

const MANIFEST_URL = `${import.meta.env.BASE_URL}data/manifest.json`;

let manifestPromise: Promise<SectionsManifest> | null = null;

export function loadManifest(): Promise<SectionsManifest> {
  if (!manifestPromise) {
    manifestPromise = fetch(MANIFEST_URL)
      .then((r) => (r.ok ? r.json() : { available: {} }))
      .catch(() => ({ available: {} }));
  }
  return manifestPromise;
}

/** Reset the manifest cache (mainly for hot-reload during development). */
export function resetManifestCache(): void {
  manifestPromise = null;
}

export function sectionUrl(parvaSlug: string, section: number): string {
  const padded = String(section).padStart(3, '0');
  return `${import.meta.env.BASE_URL}data/${parvaSlug}/${padded}.json`;
}

export async function loadSection(
  parvaSlug: string,
  section: number,
): Promise<SectionData | null> {
  try {
    const res = await fetch(sectionUrl(parvaSlug, section));
    if (!res.ok) return null;
    return (await res.json()) as SectionData;
  } catch {
    return null;
  }
}
